const words = [
  "coast",
  "car loan",
  "polka dot",
  "sticks",
  "stretch",
  "banjo",
  "goldfish",
  "form",
  "goose",
  "prose",
  "chickens",
  "latex",
  "face",
  "library",
  "circle",
  "guitar",
  "kittens",
  "worm",
  "kiss",
  "slope",
  "carrot people",
  "waste",
  "skull and crossbones",
  "cannon",
  "boat",
  "rings",
  "bad tempered nun",
  "laura",
  "shape",
  "antechamber",
  "furniture",
  "frame",
  "normal distribution",
  "window",
  "parcel",
  "tire iron",
  "double fault",
  "gentlefolk",
  "cabbage",
  "pen",
  "fourth power",
  "force",
  "poop",
  "drink",
  "lamb",
  "land",
  "coffee table",
  "cushion",
  "disk file",
  "driving",
  "reason",
  "sportswoman",
  "robin",
  "linoleum cutter",
  "lips",
  "icicle",
  "coffee pot",
  "property",
  "roll",
  "rail",
  "divergent thinking",
  "power",
  "vest",
];
export const chooseWord = () => words[Math.floor(Math.random() * words.length)];
